// PARA LAS CLASES CSS TENES QUE USAR EL ATRIBUTO className Y NO class COMO USUALMENTE ES EN HTML
// AL BAJAR EL PROYECTO TENES QUE EJECUTAR EN LA CONSOLA npm install
// A PARTIR DE AHI PARA PODER CORRER LA APP TENES QUE EJECUTAR EN LA CONSOLA npm run dev
// CUANDO EL PROGRAMA ESTE ARRIBA LA CONSOLA TE VA A MOSTRAR CON QUE URL ACCEDERLA con la linea ready - started server on ........
// PODES DEJAR EL PROGRAMA CORRIENDO MIENTRAS HACES LOS CAMBIOS Y ESTOS SE VAN A MOSTRAR EN VIVO

export default function Home() {
  return (
    <>
      <h1>TU HTML ACA</h1>
    </>
  );
}
